@extends('layouts.kasir')

@section('title', 'Transaksi Baru')

@section('content')
<!-- Floating Cart Button -->
<button id="floating_cart_btn" onclick="openCartSidebar()" style="position: fixed; bottom: 24px; right: 24px; width: 64px; height: 64px; border-radius: 50%; background: linear-gradient(135deg, var(--primary-color) 0%, #4338ca 100%); color: white; border: none; box-shadow: 0 10px 25px rgba(79, 70, 229, 0.4); cursor: pointer; z-index: 50; display: flex; align-items: center; justify-content: center; transition: transform 0.2s;">
    <i class="ri-shopping-cart-2-line" style="font-size: 1.8rem;"></i>
    <span id="cart_badge" style="display: none; position: absolute; top: -4px; right: -4px; background: #ef4444; color: white; border-radius: 50%; width: 28px; height: 28px; font-size: 0.75rem; font-weight: 700; display: flex; align-items: center; justify-content: center; border: 3px solid white;">0</span>
</button>

<!-- Main Content: Full Width Product Grid -->
<div style="padding: 0 20px;">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 24px;">
        <div>
            <h2 style="font-size: 1.5rem; font-weight: 700; color: #1f2937; margin-bottom: 4px;">Katalog Produk</h2>
            <p style="color: #6b7280; font-size: 0.9rem;">Klik produk untuk menambahkan ke keranjang</p>
        </div>
        
        <div style="display: flex; gap: 12px; align-items: center;">
            <button onclick="openHistoryModal()" style="background: white; border: 1px solid #e5e7eb; padding: 10px 16px; border-radius: 12px; font-weight: 600; color: #4b5563; cursor: pointer; display: flex; align-items: center; gap: 8px; box-shadow: 0 1px 2px rgba(0,0,0,0.05);">
                <i class="ri-history-line"></i> Riwayat
            </button>
            <div style="position: relative;">
                <select id="category_select" onchange="setCategory(this.value)" style="padding: 12px 16px; border: 1px solid #e5e7eb; border-radius: 12px; font-weight: 600; color: #4b5563; cursor: pointer; background: white; outline: none; box-shadow: 0 1px 2px rgba(0,0,0,0.05); min-width: 160px; appearance: none; background-image: url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%236b7280%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E'); background-repeat: no-repeat; background-position: right 12px top 50%; background-size: 10px auto; padding-right: 32px;">
                    <option value="all">Semua Kategori</option>
                    <!-- Options injected by JS -->
                </select>
            </div>
            <div style="position: relative; width: 350px;">
                <i class="ri-search-line" style="position: absolute; left: 14px; top: 50%; transform: translateY(-50%); color: #9ca3af; font-size: 1.1rem;"></i>
                <input type="text" id="barcode_input" 
                    class="form-input" 
                    placeholder="Cari nama barang atau scan barcode..." 
                    style="width: 100%; padding: 14px 14px 14px 44px; border: 1px solid #e5e7eb; border-radius: 12px; font-size: 1rem; box-shadow: 0 1px 2px rgba(0,0,0,0.05); transition: all 0.2s;"
                    oninput="filterProducts(this.value)"
                    onkeydown="handleScanner(event)"
                    autofocus>
            </div>
        </div>
    </div>



    <div id="product_grid" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 16px;">
        <!-- Grid generated by JS -->
    </div>
    
    <div id="no_products_msg" style="display: none; text-align: center; padding: 60px; color: #9ca3af;">
        <div style="background: #f3f4f6; width: 80px; height: 80px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 16px;">
            <i class="ri-search-2-line" style="font-size: 2.5rem; color: #d1d5db;"></i>
        </div>
        <h3 style="color: #374151; font-weight: 600; margin-bottom: 4px;">Produk tidak ditemukan</h3>
        <p style="font-size: 0.9rem;">Coba kata kunci lain atau scan ulang barcode.</p>
    </div>
</div>

<!-- Cart Sidebar (Slide from Right) -->
<div id="cart_sidebar" style="display: none; position: fixed; top: 0; right: 0; width: 550px; max-width: 90vw; height: 100vh; background: white; box-shadow: -4px 0 20px rgba(0,0,0,0.15); z-index: 100; overflow-y: auto;">
    <div style="position: sticky; top: 0; background: white; z-index: 10; padding: 20px; border-bottom: 2px solid #f3f4f6; display: flex; justify-content: space-between; align-items: center;">
        <h2 style="font-size: 1.25rem; font-weight: 700; margin: 0;">Keranjang Belanja</h2>
        <button onclick="closeCartSidebar()" style="background: #f3f4f6; border: none; width: 32px; height: 32px; border-radius: 8px; cursor: pointer; display: flex; align-items: center; justify-content: center; color: #6b7280;">
            <i class="ri-close-line" style="font-size: 1.3rem;"></i>
        </button>
    </div>

    <div style="padding: 20px;">
        <!-- Cart Items -->
        <div id="cart_items_container" style="margin-bottom: 20px;">
            <!-- Items injected by JS -->
        </div>
        
        <div id="empty_cart_msg" style="text-align: center; padding: 40px 20px; color: #9ca3af;">
            <i class="ri-shopping-cart-2-line" style="font-size: 3rem; margin-bottom: 12px; display: block; opacity: 0.5;"></i>
            <p>Keranjang masih kosong.</p>
            <p style="font-size: 0.85rem;">Pilih produk untuk memulai.</p>
        </div>

        <!-- Member Card Section -->
        <div id="member_section" style="display: none; margin-bottom: 20px; padding: 16px; background: #f9fafb; border-radius: 12px; border: 1px solid #e5e7eb;">
            <label style="display: block; margin-bottom: 8px; font-weight: 600; font-size: 0.9rem; color: #374151;">Member Card</label>
            <div style="display: flex; gap: 8px;">
                <input type="text" id="member_code_input" placeholder="Scan/Input Kode" class="form-input" style="flex: 1; padding: 10px; border: 1px solid #d1d5db; border-radius: 8px;" onkeydown="if(event.key === 'Enter') checkMemberCode()">
                <button onclick="checkMemberCode()" id="btn_check_member" style="background: #e0e7ff; color: #4338ca; border: none; padding: 0 16px; border-radius: 8px; font-weight: 600; cursor: pointer;">Cek</button>
            </div>
            <div id="member_info_display" style="display: none; margin-top: 10px; background: #ecfdf5; padding: 10px; border-radius: 8px; border: 1px solid #a7f3d0; font-size: 0.85rem;">
                <div style="display: flex; justify-content: space-between; align-items: flex-start;">
                    <div>
                        <div style="font-weight: 700; color: #065f46;" id="member_name_display">Member Name</div>
                        <div style="color: #047857;">Diskon: <span id="member_discount_percent_display">0</span>%</div>
                    </div>
                    <button onclick="removeMember()" style="font-size: 0.75rem; color: #ef4444; background: white; border: 1px solid #fecaca; padding: 2px 8px; border-radius: 4px; cursor: pointer;">Hapus</button>
                </div>
            </div>
        </div>

        <!-- Payment Method -->
        <div id="payment_section" style="display: none; margin-bottom: 20px; padding: 16px; background: #f9fafb; border-radius: 12px; border: 1px solid #e5e7eb;">
            <label style="display: block; margin-bottom: 8px; font-weight: 600; font-size: 0.9rem; color: #374151;">Metode Pembayaran</label>
            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">
                <label class="payment-option" style="cursor: pointer;">
                    <input type="radio" name="payment_method" value="cash" checked onchange="togglePaymentMethod('cash')" style="display: none;">
                    <div class="option-box" style="padding: 10px; border: 1px solid #d1d5db; border-radius: 8px; text-align: center; transition: all 0.2s;">
                        <i class="ri-money-dollar-circle-line" style="display: block; font-size: 1.2rem; margin-bottom: 4px;"></i>
                        <span style="font-size: 0.9rem; font-weight: 500;">Tunai</span>
                    </div>
                </label>
                <label class="payment-option" style="cursor: pointer;">
                    <input type="radio" name="payment_method" value="qris" onchange="togglePaymentMethod('qris')" style="display: none;">
                    <div class="option-box" style="padding: 10px; border: 1px solid #d1d5db; border-radius: 8px; text-align: center; transition: all 0.2s;">
                        <i class="ri-qr-code-line" style="display: block; font-size: 1.2rem; margin-bottom: 4px;"></i>
                        <span style="font-size: 0.9rem; font-weight: 500;">QRIS</span>
                    </div>
                </label>
            </div>
            <style>
                input[name="payment_method"]:checked + .option-box {
                    border-color: var(--primary-color);
                    background: #eef2ff;
                    color: var(--primary-color);
                    box-shadow: 0 0 0 1px var(--primary-color);
                }
            </style>

            <!-- QRIS Display -->
            <div id="qris_container" style="display: none; text-align: center; margin-top: 12px; background: #fff; padding: 16px; border-radius: 8px; border: 1px solid #e5e7eb;">
                @if(isset($qrisImage) && $qrisImage)
                    <img src="{{ asset('storage/' . $qrisImage) }}" 
                         alt="QRIS" 
                         onclick="showQrisModal(this.src)"
                         style="max-width: 150px; height: auto; border-radius: 8px; cursor: pointer; margin: 0 auto;">
                    <p style="margin-top: 8px; font-size: 0.8rem; color: #6b7280;">Klik untuk memperbesar</p>
                @else
                    <div style="padding: 20px; background: #f3f4f6; border-radius: 8px; font-size: 0.85rem; color: #6b7280;">
                        QRIS belum tersedia
                    </div>
                @endif
            </div>
        </div>

        <!-- Price Summary -->
        <div id="price_summary" style="display: none; padding: 16px; background: #f9fafb; border-radius: 12px; border: 1px solid #e5e7eb; margin-bottom: 16px;">
            <div style="display: flex; justify-content: space-between; margin-bottom: 6px; font-size: 0.9rem;">
                <span style="color: #6b7280;">Subtotal</span>
                <span style="font-weight: 600;" id="sub_total_display">Rp 0</span>
            </div>
            <div id="member_discount_row" style="display: none; justify-content: space-between; margin-bottom: 6px; font-size: 0.9rem; color: #dc2626;">
                <span>Diskon Member (<span id="discount_label_percent">0%</span>)</span>
                <span style="font-weight: 600;" id="discount_display">-Rp 0</span>
            </div>
            <div style="display: flex; justify-content: space-between; align-items: flex-end; padding-top: 12px; border-top: 2px dashed #d1d5db; margin-top: 8px;">
                <span style="font-size: 1.1rem; font-weight: 700; color: #1f2937;">Total Bayar</span>
                <span style="font-size: 1.6rem; font-weight: 800; color: var(--primary-color);" id="grand_total_display">Rp 0</span>
            </div>
        </div>
        
        <button onclick="processTransaction()" id="btn_process" disabled style="width: 100%; padding: 14px; background: #10b981; color: white; border: none; border-radius: 12px; cursor: pointer; font-size: 1.1rem; font-weight: 600; opacity: 0.5; transition: all 0.2s; box-shadow: 0 4px 6px -1px rgba(16, 185, 129, 0.2);">
            Bayar Sekarang
        </button>
    </div>
</div>

<!-- Overlay -->
<div id="cart_overlay" onclick="closeCartSidebar()" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 99;"></div>


<!-- Modal Zoom QRIS -->
<div id="qrisModal" onclick="closeQrisModal()" style="display: none; position: fixed; z-index: 9999; left: 0; top: 0; width: 100%; height: 100%; overflow: auto; background-color: rgba(0,0,0,0.85); align-items: center; justify-content: center; backdrop-filter: blur(5px);">
    <div style="position: relative; max-width: 90%; max-height: 90%;">
        <img id="qrisModalImg" style="width: auto; height: auto; max-width: 100%; max-height: 80vh; border-radius: 12px; box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04);">
        <div style="text-align: center; margin-top: 15px;">
            <span style="color: white; font-weight: 500; background: rgba(255,255,255,0.2); padding: 8px 16px; border-radius: 20px; font-size: 0.9rem;">
                <i class="ri-close-circle-line" style="vertical-align: middle;"></i> Klik sembarang untuk menutup
            </span>
        </div>
    </div>
</div>

<!-- Modal Riwayat Transaksi -->
<div id="historyModal" class="modal-overlay" style="display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%; background: rgba(0,0,0,0.5); z-index: 100; justify-content: center; align-items: center;">
    <div class="modal-content" style="background: white; width: 800px; max-width: 95%; max-height: 85vh; border-radius: 16px; display: flex; flex-direction: column; overflow: hidden; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);">
        <div style="padding: 20px; border-bottom: 1px solid #e5e7eb; display: flex; justify-content: space-between; align-items: center;">
            <h2 style="font-size: 1.25rem; font-weight: 700;">Riwayat Transaksi Terakhir</h2>
            <button onclick="closeHistoryModal()" style="background: none; border: none; font-size: 1.5rem; cursor: pointer; color: #6b7280;">
                <i class="ri-close-line"></i>
            </button>
        </div>
        <div style="overflow-y: auto; padding: 0;">
            <table style="width: 100%; border-collapse: collapse;">
                <thead style="background: #f9fafb; position: sticky; top: 0;">
                    <tr>
                        <th style="padding: 12px 20px; text-align: left; font-size: 0.85rem; color: #6b7280; font-weight: 600;">ID Transaksi</th>
                        <th style="padding: 12px 20px; text-align: left; font-size: 0.85rem; color: #6b7280; font-weight: 600;">Waktu</th>
                        <th style="padding: 12px 20px; text-align: left; font-size: 0.85rem; color: #6b7280; font-weight: 600;">Metode</th>
                        <th style="padding: 12px 20px; text-align: right; font-size: 0.85rem; color: #6b7280; font-weight: 600;">Total</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($recentTransactions as $trx)
                    <tr style="border-bottom: 1px solid #f3f4f6;">
                        <td style="padding: 12px 20px; font-family: monospace; font-weight: 500;">{{ $trx->nomor_transaksi }}</td>
                        <td style="padding: 12px 20px; color: #4b5563;">{{ \Carbon\Carbon::parse($trx->tanggal)->format('d M H:i') }}</td>
                        <td style="padding: 12px 20px;">
                            @if($trx->payment_method == 'qris')
                                <span style="background: #e0e7ff; color: #4338ca; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">QRIS</span>
                            @else
                                <span style="background: #d1fae5; color: #065f46; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600;">TUNAI</span>
                            @endif
                        </td>
                        <td style="padding: 12px 20px; text-align: right; font-weight: 600; color: #111827;">Rp {{ number_format($trx->sub_total, 0, ',', '.') }}</td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4" style="padding: 40px; text-align: center; color: #9ca3af;">Belum ada transaksi hari ini.</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
        <div style="padding: 16px; border-top: 1px solid #e5e7eb; background: #f9fafb; text-align: right;">
            <a href="{{ route('kasir.transaksi.index') }}" style="color: var(--primary-color); font-weight: 600; text-decoration: none; font-size: 0.9rem;">Lihat Semua Riwayat &rarr;</a>
        </div>
    </div>
</div>

<script>
    // DARA PRODUK SERVER
    const allProducts = @json($products);
    let cart = [];
    let currentMember = null;
    let activeCategory = 'all'; // State kategori aktif
    
    // Inisialisasi
    window.onload = function() {
        generateCategoryFilters(); // Generate pill kategori
        renderProductGrid(allProducts);
        document.getElementById('barcode_input').focus();
    };

    // Fungsi Cek Validitas Diskon
    function checkDiscountValid(product) {
        const now = new Date();
        
        if (!product.discount_percentage || product.discount_percentage <= 0) return false;
        
        // Cek Kuota
        if (product.discount_stock !== null && product.discount_stock <= 0) return false;
        
        // Cek Start Date
        if (product.discount_start) {
            // Pastikan format aman untuk Date constructor (replace space with T)
            const startDate = new Date(product.discount_start.replace(' ', 'T'));
            if (now < startDate) return false;
        }

        // Cek End Date
        if (product.discount_end) {
            const endDate = new Date(product.discount_end.replace(' ', 'T'));
            if (now > endDate) return false;
        }
        
        return true;
    }

    // Fungsi Render Grid Produk
    function renderProductGrid(products) {
        const grid = document.getElementById('product_grid');
        const noDataMsg = document.getElementById('no_products_msg');
        
        grid.innerHTML = '';
        
        if (products.length === 0) {
            grid.style.display = 'none';
            noDataMsg.style.display = 'block';
            return;
        }

        grid.style.display = 'grid';
        noDataMsg.style.display = 'none';

        products.forEach(product => {
            // Determine image source
            const imgSrc = product.image ? `/storage/${product.image}` : null;
            
            // Generate Card HTML
            const card = document.createElement('div');
            card.style.cssText = `
                background: white; 
                border-radius: 12px; 
                overflow: hidden; 
                box-shadow: 0 1px 3px rgba(0,0,0,0.1); 
                cursor: pointer; 
                transition: transform 0.2s, box-shadow 0.2s; 
                border: 1px solid #f3f4f6;
                display: flex;
                flex-direction: column;
            `;
            card.onmouseover = () => {
                card.style.transform = 'translateY(-4px)';
                card.style.boxShadow = '0 10px 15px -3px rgba(0, 0, 0, 0.1)';
            };
            card.onmouseout = () => {
                card.style.transform = 'none';
                card.style.boxShadow = '0 1px 3px rgba(0,0,0,0.1)';
            };
            card.onclick = () => addProductToCart(product, 1);

            let imageHtml = '';
            if (imgSrc) {
                imageHtml = `<div style="height: 140px; overflow: hidden; background: #f9fafb;">
                                <img src="${imgSrc}" style="width: 100%; height: 100%; object-fit: cover;" alt="${product.name}">
                             </div>`;
            } else {
                imageHtml = `<div style="height: 140px; background: linear-gradient(135deg, #f3f4f6 0%, #e5e7eb 100%); display: flex; align-items: center; justify-content: center; color: #9ca3af;">
                                <i class="ri-shopping-bag-3-line" style="font-size: 3rem;"></i>
                             </div>`;
            }

            // Stock Logic
            let stockBadge = '';
            if (product.stock <= 0) {
                stockBadge = '<span style="position: absolute; top: 10px; right: 10px; background: rgba(239, 68, 68, 0.9); color: white; padding: 4px 10px; border-radius: 20px; font-size: 0.75rem; font-weight: 600;">Habis</span>';
                card.style.opacity = '0.6';
                card.style.pointerEvents = 'none';
            } else if (product.stock < 10) {
                stockBadge = `<span style="position: absolute; top: 10px; right: 10px; background: rgba(245, 158, 11, 0.9); color: white; padding: 4px 10px; border-radius: 20px; font-size: 0.75rem; font-weight: 600; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">Sisa ${product.stock}</span>`;
            }

            // Discount Badge
            let discountBadge = '';
            
            const isDiscountActive = checkDiscountValid(product);
            
            if (isDiscountActive) {
                let limitText = '';
                if (product.discount_stock !== null) {
                    limitText = `<div style="font-size: 0.65rem; background: rgba(0,0,0,0.2); border-radius: 10px; padding: 2px 6px; margin-top: 2px; text-align: center;">Sisa Promo: ${product.discount_stock}</div>`;
                }
                
                discountBadge = `<div style="position: absolute; top: 10px; left: 10px; display: flex; flex-direction: column; align-items: flex-start;">
                    <span style="background: linear-gradient(135deg, #ef4444 0%, #dc2626 100%); color: white; padding: 4px 10px; border-radius: 20px; font-size: 0.75rem; font-weight: 700; box-shadow: 0 2px 8px rgba(239, 68, 68, 0.4);">
                        <i class="ri-price-tag-3-fill"></i> ${Math.round(product.discount_percentage)}% OFF
                    </span>
                    ${limitText}
                </div>`;
            }

            card.innerHTML = `
                <div style="position: relative;">
                    ${imageHtml}
                    ${discountBadge}
                    ${stockBadge}
                </div>
                <div style="padding: 16px; flex: 1; display: flex; flex-direction: column;">
                    <div style="font-size: 0.8rem; color: #9ca3af; margin-bottom: 4px; display: flex; justify-content: space-between;">
                        <span>${product.product_code}</span>
                        <span style="color: ${product.stock < 10 ? '#f59e0b' : '#10b981'}; font-weight: 600;">
                            ${product.stock < 10 ? '<i class="ri-alert-line"></i> ' : ''}Stok: ${product.stock}
                        </span>
                    </div>
                    <h3 style="font-size: 1rem; font-weight: 600; color: #1f2937; margin: 0 0 8px 0; line-height: 1.4; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden;">${product.name}</h3>
                    <div style="margin-top: auto;">
                        ${isDiscountActive ? `
                            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 4px;">
                                <span style="font-size: 0.8rem; color: #9ca3af; text-decoration: line-through;">${formatRupiah(product.selling_price)}</span>
                            </div>
                            <div style="display: flex; align-items: center; justify-content: space-between;">
                                <span style="font-weight: 700; color: #dc2626; font-size: 1.1rem;">${formatRupiah(product.final_price || product.selling_price)}</span>
                                <button style="background: #fee2e2; color: #dc2626; border: none; width: 32px; height: 32px; border-radius: 8px; display: flex; align-items: center; justify-content: center; transition: background 0.2s;">
                                    <i class="ri-add-line" style="font-weight: 600;"></i>
                                </button>
                            </div>
                        ` : `
                            <div style="display: flex; align-items: center; justify-content: space-between;">
                                <span style="font-weight: 700; color: var(--primary-color); font-size: 1.05rem;">${formatRupiah(product.selling_price)}</span>
                                <button style="background: #e0e7ff; color: var(--primary-color); border: none; width: 32px; height: 32px; border-radius: 8px; display: flex; align-items: center; justify-content: center; transition: background 0.2s;">
                                    <i class="ri-add-line" style="font-weight: 600;"></i>
                                </button>
                            </div>
                        `}
                    </div>
                </div>
            `;

            grid.appendChild(card);
        });
    }

    // Generate Filter Kategori (Dropdown)
    function generateCategoryFilters() {
        const categories = [...new Set(allProducts.map(p => p.category).filter(c => c))].sort();
        const select = document.getElementById('category_select');
        
        let options = '<option value="all">Semua Kategori</option>';
        
        categories.forEach(cat => {
            // Encode value just in case
            const safeValue = cat.replace(/"/g, '&quot;');
            const isSelected = activeCategory === cat ? 'selected' : '';
            options += `<option value="${safeValue}" ${isSelected}>${cat}</option>`;
        });
        
        select.innerHTML = options;
    }

    // Set Active Category
    function setCategory(cat) {
        activeCategory = cat;
        applyFilters();
    }

    // Gabungan Filter Search & Category
    function applyFilters() {
        const query = document.getElementById('barcode_input').value.toLowerCase().trim();
        
        const filtered = allProducts.filter(p => {
            // Match Search
            const matchSearch = p.name.toLowerCase().includes(query) || 
                                p.product_code.toLowerCase().startsWith(query);
            
            // Match Category
            const matchCategory = activeCategory === 'all' || p.category === activeCategory;
            
            return matchSearch && matchCategory;
        });
        
        renderProductGrid(filtered);
    }
    
    // Redirect old filter function to new one
    function filterProducts(val) {
        applyFilters();
    }

    // Handle Scanner (Enter Key)
    function handleScanner(event) {
        if (event.key === 'Enter') {
            event.preventDefault();
            const inputVal = event.target.value.trim();
            if (!inputVal) return;

            // Cari exact match
            const exactProduct = allProducts.find(p => p.product_code.toLowerCase() === inputVal.toLowerCase());
            
            if (exactProduct) {
                addProductToCart(exactProduct, 1);
                event.target.value = ''; // Clear input siap scan lagi
                filterProducts(''); // Reset grid
            } else {
                // Jangan clear jika tidak ketemu, mungkin user sedang mengetik nama
                // Tapi user menekan Enter, jadi mungkin mereka berharap ada aksi
                // Opsional: Play error sound
                alert('Barang dengan kode tersebut tidak ditemukan!');
            }
        }
    }

    // Tambah ke Cart
    function addProductToCart(product, qty) {
        if (product.stock <= 0) return alert('Stok habis!');

        // Logic Harga: Cek validitas diskon (time & quota)
        const isDiscountActive = checkDiscountValid(product);
        
        const effectivePrice = isDiscountActive 
            ? (product.final_price || product.selling_price) 
            : product.selling_price;
            
        // Validasi quota jika user nambah item di cart melebihi stok promo
        // Untuk sekarang biarkan simple: jika promo aktif saat klik, masukkan harga promo.
        // Nanti backend yang akan reject atau potong kuota.
        
        const existingItem = cart.find(item => item.product_id == product.id);
        
        if (existingItem) {
            if (existingItem.quantity + qty > product.stock) {
                return alert('Stok tidak mencukupi!');
            }
            // Jika harga berubah (misal tadi diskon skrg expired), update harga?
            // Biasanya cart mengunci harga saat add.
            // Biarkan harga lama untuk item yg sdh ada, atau update.
            // Kita update saja agar fair.
            // existingItem.price = effectivePrice; 
            // ^ Jangan update harga eksisting, nanti user bingung. 
            // Tapi itemnya sama.
            // Asumsikan harga sama.
            
            existingItem.quantity += qty;
            existingItem.total = existingItem.quantity * existingItem.price; // Use price already in cart
        } else {
            cart.push({
                product_id: product.id,
                name: product.name,
                price: effectivePrice,
                original_price: product.selling_price,
                discount_percentage: isDiscountActive ? (product.discount_percentage || 0) : 0,
                stock: product.stock,
                image: product.image, // Save image ref for cart if needed
                quantity: qty,
                total: qty * effectivePrice
            });
        }
        
        renderCart();
    }

    // Render Cart (Div Based)
    function renderCart() {
        const container = document.getElementById('cart_items_container');
        container.innerHTML = '';
        
        let subTotal = 0;

        cart.forEach((item, index) => {
            subTotal += item.total;
            
            const itemDiv = document.createElement('div');
            itemDiv.style.cssText = 'display: flex; gap: 12px; margin-bottom: 12px; padding-bottom: 12px; border-bottom: 1px dashed #e5e7eb; align-items: center;';
            
            // Tiny Image
            const imgHtml = item.image 
                ? `<img src="/storage/${item.image}" style="width: 40px; height: 40px; object-fit: cover; border-radius: 6px; background: #f3f4f6;">`
                : `<div style="width: 40px; height: 40px; border-radius: 6px; background: #f3f4f6; display: flex; align-items: center; justify-content: center; color: #9ca3af;"><i class="ri-shopping-bag-3-fill"></i></div>`;

            itemDiv.innerHTML = `
                ${imgHtml}
                <div style="flex: 1;">
                    <div style="font-weight: 600; font-size: 0.9rem; color: #374151; line-height: 1.2; margin-bottom: 2px;">${item.name}</div>
                    <div style="font-size: 0.8rem; color: #6b7280;">
                        ${item.discount_percentage > 0 ? `
                            <span style="text-decoration: line-through; color: #9ca3af; margin-right: 4px;">${formatRupiah(item.original_price)}</span>
                            <span style="color: #dc2626; font-weight: 600;">${formatRupiah(item.price)}</span>
                        ` : formatRupiah(item.price)}
                    </div>
                </div>
                <div style="text-align: right;">
                    <button onclick="removeFromCart(${index})" style="color: #ef4444; background: none; border: none; cursor: pointer; padding: 2px; margin-bottom: 2px; font-size: 0.8rem;">
                        <i class="ri-delete-bin-line"></i>
                    </button>
                    <div style="display: flex; align-items: center; gap: 6px; background: #f3f4f6; border-radius: 6px; padding: 2px;">
                        <button onclick="updateQty(${index}, -1)" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center; border: none; background: white; border-radius: 4px; cursor: pointer; font-weight: bold; color: #4b5563;">-</button>
                        <span style="font-size: 0.85rem; font-weight: 600; min-width: 16px; text-align: center;">${item.quantity}</span>
                        <button onclick="updateQty(${index}, 1)" style="width: 20px; height: 20px; display: flex; align-items: center; justify-content: center; border: none; background: white; border-radius: 4px; cursor: pointer; font-weight: bold; color: #4b5563;">+</button>
                    </div>
                </div>
            `;
            container.appendChild(itemDiv);
        });

        // Calculate Totals
        let discountAmount = 0;
        if (currentMember) {
            discountAmount = subTotal * (currentMember.discount_percentage / 100);
            
            // Update Discount UI
            document.getElementById('member_discount_row').style.display = 'flex';
            document.getElementById('discount_label_percent').innerText = currentMember.discount_percentage + '%';
            document.getElementById('discount_display').innerText = '- ' + formatRupiah(discountAmount);
        } else {
            document.getElementById('member_discount_row').style.display = 'none';
        }

        const grandTotal = subTotal - discountAmount;

        document.getElementById('sub_total_display').innerText = formatRupiah(subTotal);
        document.getElementById('grand_total_display').innerText = formatRupiah(grandTotal);
        
        const emptyMsg = document.getElementById('empty_cart_msg');
        const btnProcess = document.getElementById('btn_process');
        
        // Show/Hide sections based on cart
        const memberSection = document.getElementById('member_section');
        const paymentSection = document.getElementById('payment_section');
        const priceSection = document.getElementById('price_summary');
        
        if (cart.length > 0) {
            emptyMsg.style.display = 'none';
            memberSection.style.display = 'block';
            paymentSection.style.display = 'block';
            priceSection.style.display = 'block';
            btnProcess.disabled = false;
            btnProcess.style.opacity = 1;
            btnProcess.style.boxShadow = '0 4px 6px -1px rgba(16, 185, 129, 0.4)';
        } else {
            emptyMsg.style.display = 'block';
            memberSection.style.display = 'none';
            paymentSection.style.display = 'none';
            priceSection.style.display = 'none';
            btnProcess.disabled = true;
            btnProcess.style.opacity = 0.5;
            btnProcess.style.boxShadow = 'none';
        }
        
        // Update cart badge
        updateCartBadge();
    }

    function updateCartBadge() {
        const badge = document.getElementById('cart_badge');
        const totalItems = cart.reduce((sum, item) => sum + item.quantity, 0);
        
        if (totalItems > 0) {
            badge.style.display = 'flex';
            badge.innerText = totalItems;
        } else {
            badge.style.display = 'none';
        }
    }

    function openCartSidebar() {
        document.getElementById('cart_sidebar').style.display = 'block';
        document.getElementById('cart_overlay').style.display = 'block';
        document.body.style.overflow = 'hidden';
    }

    function closeCartSidebar() {
        document.getElementById('cart_sidebar').style.display = 'none';
        document.getElementById('cart_overlay').style.display = 'none';
        document.body.style.overflow = 'auto';
    }

    function updateQty(index, change) {
        const item = cart[index];
        const newQty = item.quantity + change;
        
        if (newQty <= 0) {
            if(confirm('Hapus item ini?')) { // Simple confirm is fine
                removeFromCart(index);
            }
            return;
        }
        if (newQty > item.stock) return alert('Stok mentok! Sisa: ' + item.stock);

        item.quantity = newQty;
        item.total = item.quantity * item.price;
        renderCart();
    }

    function removeFromCart(index) {
        cart.splice(index, 1);
        renderCart();
    }

    function togglePaymentMethod(method) {
        // If passed from radio, use arg. If from select (removed), update.
        // We used radio in new HTML.
        const qrisContainer = document.getElementById('qris_container');
        if (method === 'qris') {
            qrisContainer.style.display = 'block';
        } else {
            qrisContainer.style.display = 'none';
        }
    }

    function showQrisModal(src) {
        const modal = document.getElementById('qrisModal');
        const modalImg = document.getElementById('qrisModalImg');
        modal.style.display = "flex";
        modalImg.src = src;
        document.body.style.overflow = 'hidden';
    }

    function closeQrisModal() {
        const modal = document.getElementById('qrisModal');
        modal.style.display = "none";
        document.body.style.overflow = 'auto';
    }

    function openHistoryModal() {
        document.getElementById('historyModal').style.display = 'flex';
    }

    function closeHistoryModal() {
        document.getElementById('historyModal').style.display = 'none';
    }

    function formatRupiah(number) {
        return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(number);
    }

    async function processTransaction() {
        if (!cart.length) return alert('Keranjang kosong!');
        if (!confirm('Proses pembayaran?')) return;

        const btnProcess = document.getElementById('btn_process');
        const originalText = btnProcess.innerText;
        btnProcess.disabled = true;
        btnProcess.innerHTML = '<i class="ri-loader-4-line ri-spin"></i> Memproses...';

        try {
            // Get selected radio
            const paymentMethod = document.querySelector('input[name="payment_method"]:checked').value;

            const response = await fetch("{{ route('kasir.transaksi.store') }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRF-TOKEN": "{{ csrf_token() }}"
                },
                body: JSON.stringify({ 
                    items: cart,
                    payment_method: paymentMethod,
                    member_code: currentMember ? currentMember.code : null
                })
            });

            const result = await response.json();

            if (result.success) {
                // alert('Transaksi Berhasil!'); 
                // Maybe a nicer toast later, but alert is robust
                window.location.href = result.redirect;
            } else {
                alert('Gagal: ' + result.message);
                btnProcess.disabled = false;
                btnProcess.innerText = originalText;
            }
        } catch (error) {
            console.error(error);
            alert('Terjadi kesalahan koneksi.');
            btnProcess.disabled = false;
            btnProcess.innerText = originalText;
        }
    }

    async function checkMemberCode() {
        const input = document.getElementById('member_code_input');
        const btn = document.getElementById('btn_check_member');
        const code = input.value.trim();
        
        if (!code) return alert('Silakan input kode member');
        
        const originalText = btn.innerText;
        btn.disabled = true;
        btn.innerText = '...';
        
        try {
            const response = await fetch("{{ route('kasir.check-member') }}", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    "X-CSRF-TOKEN": "{{ csrf_token() }}"
                },
                body: JSON.stringify({ member_code: code })
            });
            
            const result = await response.json();
            
            if (result.success) {
                currentMember = result.member;
                
                // Show info
                document.getElementById('member_info_display').style.display = 'block';
                document.getElementById('member_name_display').innerText = result.member.name;
                document.getElementById('member_discount_percent_display').innerText = result.member.discount_percentage; // +0 handling later
                
                // Disable input
                input.disabled = true;
                btn.style.display = 'none';
                
                renderCart(); // Recalculate totals
                // alert(result.message);
            } else {
                alert(result.message);
                input.value = '';
                input.focus();
            }
        } catch (e) {
            alert('Error checking member');
        } finally {
            btn.disabled = false;
            btn.innerText = originalText;
        }
    }

    function removeMember() {
        currentMember = null;
        
        const input = document.getElementById('member_code_input');
        input.value = '';
        input.disabled = false;
        input.focus();
        
        document.getElementById('btn_check_member').style.display = 'inline-block';
        document.getElementById('member_info_display').style.display = 'none';
        
        renderCart();
    }
</script>
@endsection
